CREATE TABLE `themes` (
  `theme_id` int(3) NOT NULL,
  `theme` varchar(200) COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`theme_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
INSERT INTO themes (theme_id, theme) VALUES (1, 'How Well Do You Know God?');
INSERT INTO themes (theme_id, theme) VALUES (2, 'Will You Be a Survivor of the Last Days?');
INSERT INTO themes (theme_id, theme) VALUES (3, 'Serving With Jehovah\'s Unified Organization');
INSERT INTO themes (theme_id, theme) VALUES (4, 'Evidence of God in the World Around Us');
INSERT INTO themes (theme_id, theme) VALUES (5, 'Family Life That Warms the Heart');
INSERT INTO themes (theme_id, theme) VALUES (6, 'The Flood of Noah\'s Day Has Meaning for Us');
INSERT INTO themes (theme_id, theme) VALUES (7, 'Mercy, a Dominant Quality of True Christians');
INSERT INTO themes (theme_id, theme) VALUES (8, 'Living, Not for Self, But to Do God\'s Will');
INSERT INTO themes (theme_id, theme) VALUES (9, 'Never Become Dull in Your Hearing');
INSERT INTO themes (theme_id, theme) VALUES (10, 'Conducting Ourselves Honestly at All Times');
INSERT INTO themes (theme_id, theme) VALUES (11, '\"No Part of the World\" - In Imitation of Christ');
INSERT INTO themes (theme_id, theme) VALUES (12, 'Respect for Authority Is a Safeguard for You');
INSERT INTO themes (theme_id, theme) VALUES (13, 'A Godly View of Sex and Marriage');
INSERT INTO themes (theme_id, theme) VALUES (14, 'A Clean People Honors Jehovah');
INSERT INTO themes (theme_id, theme) VALUES (15, 'As Christians, We Care About Other People');
INSERT INTO themes (theme_id, theme) VALUES (16, 'Keep Growing in Your Relationship With God');
INSERT INTO themes (theme_id, theme) VALUES (17, 'Glorifying God With All We Have');
INSERT INTO themes (theme_id, theme) VALUES (18, 'Are You Really Making Jehovah Your Stronghold?');
INSERT INTO themes (theme_id, theme) VALUES (19, 'Your Future - How Can It Be Known?');
INSERT INTO themes (theme_id, theme) VALUES (20, 'Is It Time for God to Rule the World?');
INSERT INTO themes (theme_id, theme) VALUES (21, 'How Do You Fit Into the Kingdom Arrangement?');
INSERT INTO themes (theme_id, theme) VALUES (22, 'Are You Content With Jehovah\'s Provisions?');
INSERT INTO themes (theme_id, theme) VALUES (23, 'Life Does Have a Purpose');
INSERT INTO themes (theme_id, theme) VALUES (24, 'What God\'s Rulership Can Do for Us');
INSERT INTO themes (theme_id, theme) VALUES (25, 'Resisting the Spirit of the World');
INSERT INTO themes (theme_id, theme) VALUES (26, 'Does God Count You Personally Important?');
INSERT INTO themes (theme_id, theme) VALUES (27, 'Getting Marriage Off to a Good Start');
INSERT INTO themes (theme_id, theme) VALUES (28, 'Show Respect and Love in Your Marriage');
INSERT INTO themes (theme_id, theme) VALUES (29, 'Responsibilities and Rewards of Parenthood');
INSERT INTO themes (theme_id, theme) VALUES (30, 'Communication - Within the Family and With God');
INSERT INTO themes (theme_id, theme) VALUES (31, 'Happy Though Hungry - How Can It Be?');
INSERT INTO themes (theme_id, theme) VALUES (32, 'Coping With Life\'s Anxieties');
INSERT INTO themes (theme_id, theme) VALUES (33, 'What Is Behind the Spirit of Rebellion?');
INSERT INTO themes (theme_id, theme) VALUES (34, 'Are You \"Marked\" for Survival?');
INSERT INTO themes (theme_id, theme) VALUES (35, 'Can You Live Forever? Will You?');
INSERT INTO themes (theme_id, theme) VALUES (36, 'Is This Life All There Is?');
INSERT INTO themes (theme_id, theme) VALUES (37, 'Decide Now for Divine Rulership');
INSERT INTO themes (theme_id, theme) VALUES (38, 'Act Wisely as the End Draws Near');
INSERT INTO themes (theme_id, theme) VALUES (39, 'Be Confident of Divine Victory!');
INSERT INTO themes (theme_id, theme) VALUES (40, 'What the Near Future Holds!');
INSERT INTO themes (theme_id, theme) VALUES (41, '\"Stand Still and See the Salvation of Jehovah\"');
INSERT INTO themes (theme_id, theme) VALUES (42, 'How the Kingdom of God Affects You');
INSERT INTO themes (theme_id, theme) VALUES (43, 'Are You Doing What God Requires of You?');
INSERT INTO themes (theme_id, theme) VALUES (44, 'Keep Seeking God\'s Kingdom');
INSERT INTO themes (theme_id, theme) VALUES (45, 'Follow the Way to Life');
INSERT INTO themes (theme_id, theme) VALUES (46, 'Maintain Your Confidence Firm to the End');
INSERT INTO themes (theme_id, theme) VALUES (47, '\"Have Faith in the Good News\"');
INSERT INTO themes (theme_id, theme) VALUES (48, 'Meeting the Test of Christian Loyalty');
INSERT INTO themes (theme_id, theme) VALUES (49, 'A Cleansed Earth - Will You Live to See It?');
INSERT INTO themes (theme_id, theme) VALUES (50, 'Decisions You Face - How Will You Make Them?');
INSERT INTO themes (theme_id, theme) VALUES (51, 'Is the Truth Transforming Your Life?');
INSERT INTO themes (theme_id, theme) VALUES (52, 'Who Is Your God?');
INSERT INTO themes (theme_id, theme) VALUES (53, 'Does Your Thinking Agree With God\'s?');
INSERT INTO themes (theme_id, theme) VALUES (54, 'Build Your Faith in Man\'s Maker');
INSERT INTO themes (theme_id, theme) VALUES (55, 'What Kind of Name Are You Making With God?');
INSERT INTO themes (theme_id, theme) VALUES (56, 'Into the New World Under Christ\'s Leadership');
INSERT INTO themes (theme_id, theme) VALUES (57, 'Bearing Up Under Persecution');
INSERT INTO themes (theme_id, theme) VALUES (58, 'How Should You Serve God?');
INSERT INTO themes (theme_id, theme) VALUES (59, 'You Will Reap What You Sow');
INSERT INTO themes (theme_id, theme) VALUES (60, 'How Purposeful Is Your Life?');
INSERT INTO themes (theme_id, theme) VALUES (61, 'On Whose Promises Do You Rely?');
INSERT INTO themes (theme_id, theme) VALUES (62, 'The Only Cure for Sick Mankind');
INSERT INTO themes (theme_id, theme) VALUES (63, 'Do You Have the Evangelizing Spirit?');
INSERT INTO themes (theme_id, theme) VALUES (64, 'Lovers of Pleasure or Lovers of God?');
INSERT INTO themes (theme_id, theme) VALUES (65, 'Finding Honor and Joy in God\'s Ministry');
INSERT INTO themes (theme_id, theme) VALUES (66, 'Slave for the Master of the Harvest');
INSERT INTO themes (theme_id, theme) VALUES (67, 'Taking Time to Meditate on Spiritual Things');
INSERT INTO themes (theme_id, theme) VALUES (68, 'Do You Harbor Resentment, or Do You Forgive?');
INSERT INTO themes (theme_id, theme) VALUES (69, 'Renewing the Spirit of Self-Sacrifice');
INSERT INTO themes (theme_id, theme) VALUES (70, 'Make Jehovah Your Confidence');
INSERT INTO themes (theme_id, theme) VALUES (71, 'How to Keep Spiritually Awake');
INSERT INTO themes (theme_id, theme) VALUES (72, 'Love Identifies the True Christian Congregation');
INSERT INTO themes (theme_id, theme) VALUES (73, 'Acquiring a Heart of Wisdom');
INSERT INTO themes (theme_id, theme) VALUES (74, 'Jehovah\'s Eyes Are Upon Us');
INSERT INTO themes (theme_id, theme) VALUES (75, 'Do You Recognize Jehovah\'s Sovereignty in Your Personal Life?');
INSERT INTO themes (theme_id, theme) VALUES (76, 'Bible Principles - Can They Help Us to Cope With Today\'s Problems?');
INSERT INTO themes (theme_id, theme) VALUES (77, 'Follow the Course of Hospitality');
INSERT INTO themes (theme_id, theme) VALUES (78, 'Serve Jehovah With a Joyful Heart');
INSERT INTO themes (theme_id, theme) VALUES (79, 'Friendship With God, Friendship With the World - Which Will You Choose?');
INSERT INTO themes (theme_id, theme) VALUES (80, 'Does Your Hope Rest on Science or the Bible?');
INSERT INTO themes (theme_id, theme) VALUES (81, 'Who Are Qualified as Ministers of God?');
INSERT INTO themes (theme_id, theme) VALUES (82, 'Jehovah and Christ - Are They Part of a Trinity?');
INSERT INTO themes (theme_id, theme) VALUES (83, 'Religion\'s Time of Judgment');
INSERT INTO themes (theme_id, theme) VALUES (84, 'Will You Escape This World\'s Destiny?');
INSERT INTO themes (theme_id, theme) VALUES (85, 'Good News in a Violent World');
INSERT INTO themes (theme_id, theme) VALUES (86, 'Prayers That Are Heard by God');
INSERT INTO themes (theme_id, theme) VALUES (87, 'What Is Your Relationship With God?');
INSERT INTO themes (theme_id, theme) VALUES (88, 'Why Live by Bible Standards?');
INSERT INTO themes (theme_id, theme) VALUES (89, 'Come, You Who Thirst for the Truth!');
INSERT INTO themes (theme_id, theme) VALUES (90, 'Reach Out for the Real Life!');
INSERT INTO themes (theme_id, theme) VALUES (91, 'The Messiah\'s Presence and His Rule');
INSERT INTO themes (theme_id, theme) VALUES (92, 'Religion\'s Role in World Affairs');
INSERT INTO themes (theme_id, theme) VALUES (93, '\"Acts of God\" - How Do You View Them?');
INSERT INTO themes (theme_id, theme) VALUES (94, 'True Religion Meets the Needs of Human Society');
INSERT INTO themes (theme_id, theme) VALUES (95, 'The Bible\'s View of Spiritistic Practices');
INSERT INTO themes (theme_id, theme) VALUES (96, 'False Religion\'s End Is Near');
INSERT INTO themes (theme_id, theme) VALUES (97, 'Remaining Blameless Amid a Crooked Generation');
INSERT INTO themes (theme_id, theme) VALUES (98, 'Keep Clean From Worldly Defilements');
INSERT INTO themes (theme_id, theme) VALUES (99, 'Why You Can Trust the Bible');
INSERT INTO themes (theme_id, theme) VALUES (100, 'True Friendship With God and Neighbor');
INSERT INTO themes (theme_id, theme) VALUES (101, 'Jehovah - The Grand Creator');
INSERT INTO themes (theme_id, theme) VALUES (102, 'Paying Attention to the Prophetic Word');
INSERT INTO themes (theme_id, theme) VALUES (103, 'You Can Find Joy in Serving God');
INSERT INTO themes (theme_id, theme) VALUES (104, 'Parents - Are You Building With Fire-Resistant Materials?');
INSERT INTO themes (theme_id, theme) VALUES (105, 'Gaining Comfort in All Our Tribulations');
INSERT INTO themes (theme_id, theme) VALUES (106, 'Ruining the Earth Brings Divine Retribution');
INSERT INTO themes (theme_id, theme) VALUES (107, 'Hold a Good Conscience in a Sinful World');
INSERT INTO themes (theme_id, theme) VALUES (108, 'Overcoming Fear of the Future');
INSERT INTO themes (theme_id, theme) VALUES (109, 'The Kingdom of God Is Near');
INSERT INTO themes (theme_id, theme) VALUES (110, 'God Comes First in Successful Family Life');
INSERT INTO themes (theme_id, theme) VALUES (111, 'What Does the Healing of the Nations Accomplish?');
INSERT INTO themes (theme_id, theme) VALUES (112, 'How to Express Love in a Lawless World');
INSERT INTO themes (theme_id, theme) VALUES (113, 'How Can Youths Cope With Today\'s Crisis?');
INSERT INTO themes (theme_id, theme) VALUES (114, 'Appreciating Marvels of God\'s Creation');
INSERT INTO themes (theme_id, theme) VALUES (115, 'How to Protect Ourselves From Satan\'s Snares');
INSERT INTO themes (theme_id, theme) VALUES (116, 'Choose Your Associates Wisely!');
INSERT INTO themes (theme_id, theme) VALUES (117, 'How to Conquer Evil With Good');
INSERT INTO themes (theme_id, theme) VALUES (118, 'Looking at Youths From Jehovah\'s Standpoint');
INSERT INTO themes (theme_id, theme) VALUES (119, 'Christian Separateness From the World - Why Beneficial');
INSERT INTO themes (theme_id, theme) VALUES (120, 'Why Submit to God\'s Rulership Now');
INSERT INTO themes (theme_id, theme) VALUES (121, 'A Worldwide Brotherhood Saved From Calamity');
INSERT INTO themes (theme_id, theme) VALUES (122, 'Global Peace - From What Source?');
INSERT INTO themes (theme_id, theme) VALUES (123, 'Why Christians Must Be Different');
INSERT INTO themes (theme_id, theme) VALUES (124, 'Basis for Confidence in the Bible\'s Divine Authorship');
INSERT INTO themes (theme_id, theme) VALUES (125, 'Why Mankind Needs a Ransom');
INSERT INTO themes (theme_id, theme) VALUES (126, 'Who Can Be Saved?');
INSERT INTO themes (theme_id, theme) VALUES (127, 'What Happens When We Die?');
INSERT INTO themes (theme_id, theme) VALUES (128, 'Is Hell Really a Place of Fiery Torment?');
INSERT INTO themes (theme_id, theme) VALUES (129, 'Is the Trinity a Scriptural Teaching?');
INSERT INTO themes (theme_id, theme) VALUES (130, 'The Earth Will Remain Forever');
INSERT INTO themes (theme_id, theme) VALUES (131, 'Is There Really a Devil?');
INSERT INTO themes (theme_id, theme) VALUES (132, 'The Resurrection - Victory Over Death!');
INSERT INTO themes (theme_id, theme) VALUES (133, 'The Origin of Humans - Does It Matter What You Believe?');
INSERT INTO themes (theme_id, theme) VALUES (134, 'Should Christians Keep the Sabbath?');
INSERT INTO themes (theme_id, theme) VALUES (135, 'The Sacredness of Life and Blood');
INSERT INTO themes (theme_id, theme) VALUES (136, 'Does God Approve of the Use of Images in Worship?');
INSERT INTO themes (theme_id, theme) VALUES (137, 'Did the Miracles of the Bible Really Happen?');
INSERT INTO themes (theme_id, theme) VALUES (138, 'Live With Soundness of Mind in a Depraved World');
INSERT INTO themes (theme_id, theme) VALUES (139, 'Godly Wisdom in a Scientific World');
INSERT INTO themes (theme_id, theme) VALUES (140, 'Jesus Christ - Earth\'s New Ruler');
INSERT INTO themes (theme_id, theme) VALUES (141, 'Human Creation\'s Groaning - When Will It End?');
INSERT INTO themes (theme_id, theme) VALUES (142, 'Why Take Refuge in Jehovah');
INSERT INTO themes (theme_id, theme) VALUES (143, 'Trust in the God of All Comfort');
INSERT INTO themes (theme_id, theme) VALUES (144, 'A Loyal Congregation Under Christ\'s Leadership');
INSERT INTO themes (theme_id, theme) VALUES (145, 'Who Is Like Jehovah Our God?');
INSERT INTO themes (theme_id, theme) VALUES (146, 'Use Education to Praise Jehovah');
INSERT INTO themes (theme_id, theme) VALUES (147, 'Trust in Jehovah\'s Saving Power');
INSERT INTO themes (theme_id, theme) VALUES (148, 'Do You Share God\'s View of Life?');
INSERT INTO themes (theme_id, theme) VALUES (149, 'Are You Walking With God?');
INSERT INTO themes (theme_id, theme) VALUES (150, 'How Real Is God to You?');
INSERT INTO themes (theme_id, theme) VALUES (151, 'Jehovah Is \"a Secure Height\" for His People');
INSERT INTO themes (theme_id, theme) VALUES (152, 'The Real Armageddon - Why? When?');
INSERT INTO themes (theme_id, theme) VALUES (153, 'Keep Close in Mind the \"Fear-Inspiring Day\"!');
INSERT INTO themes (theme_id, theme) VALUES (154, 'Human Rule - Weighed in the Balance');
INSERT INTO themes (theme_id, theme) VALUES (155, 'Has Babylon\'s Judgment Hour Arrived?');
INSERT INTO themes (theme_id, theme) VALUES (156, 'Judgment Day - ATime of Fear or Hope?');
INSERT INTO themes (theme_id, theme) VALUES (157, 'How True Christians Adorn Divine Teaching');
INSERT INTO themes (theme_id, theme) VALUES (158, 'Be Courageous, and Trust in Jehovah');
INSERT INTO themes (theme_id, theme) VALUES (159, 'Finding Security in a Dangerous World');
INSERT INTO themes (theme_id, theme) VALUES (160, 'Safeguard Your Christian Identity!');
INSERT INTO themes (theme_id, theme) VALUES (161, 'Why Did Jesus Suffer and Die?');
INSERT INTO themes (theme_id, theme) VALUES (162, 'Deliverance From a World of Darkness');
INSERT INTO themes (theme_id, theme) VALUES (163, 'Why Fear the True God?');
INSERT INTO themes (theme_id, theme) VALUES (164, 'Is God Still in Control?');
INSERT INTO themes (theme_id, theme) VALUES (165, 'Whose Values Do You Cherish?');
INSERT INTO themes (theme_id, theme) VALUES (166, 'Facing the Future With Faith and Courage');
INSERT INTO themes (theme_id, theme) VALUES (167, 'Act Wisely in a Senseless World');
INSERT INTO themes (theme_id, theme) VALUES (168, 'You Can Feel Safe in This Troubled World!');
INSERT INTO themes (theme_id, theme) VALUES (169, 'Why Be Guided by the Bible?');
INSERT INTO themes (theme_id, theme) VALUES (170, 'Who Is Qualified to Rule Mankind?');
INSERT INTO themes (theme_id, theme) VALUES (171, 'You Can Enjoy Life in Peace Now - And Forever!');
INSERT INTO themes (theme_id, theme) VALUES (172, 'What Is Your Standing With God?');
INSERT INTO themes (theme_id, theme) VALUES (173, 'Is There a True Religion From God\'s Standpoint?');
INSERT INTO themes (theme_id, theme) VALUES (174, 'God\'s New World - Who Will Qualify to Enter?');
INSERT INTO themes (theme_id, theme) VALUES (175, 'What Marks the Bible as Authentic?');
INSERT INTO themes (theme_id, theme) VALUES (176, 'Real Peace and Security - When?');
INSERT INTO themes (theme_id, theme) VALUES (177, 'Where Can You Get Help in Times of Distress?');
INSERT INTO themes (theme_id, theme) VALUES (178, 'Walk in the Way of Integrity');
INSERT INTO themes (theme_id, theme) VALUES (179, 'Reject Worldly Fantasies, Pursue Kingdom Realities');
INSERT INTO themes (theme_id, theme) VALUES (180, 'The Resurrection - Why That Hope Should Be Real to You');
INSERT INTO themes (theme_id, theme) VALUES (181, 'Is It Later Than You Think?');
INSERT INTO themes (theme_id, theme) VALUES (182, 'What God\'s Kingdom Is Doing for Us Now');
INSERT INTO themes (theme_id, theme) VALUES (183, 'Turn Your Eyes Away From Worthless Things!');